title: fbakkensen
author:
  name: Flemming Bakkensen
  email: flemming.bakkensen@gmail.com

description: >-
  Let's Nerd Out.
baseurl: "/"
url: "https://fbakkensen.github.io"
github_username: FBakkensen
show_downloads: false

# Theme settings
# Using custom terminal-style theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

#site
paginate: 5         # Posts per page
paginate_path: "/page:num/"  # URL structure for paginated pages
google_analytics: G-5FQ1BD5CNH # Google Analytics tracking ID

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  auto_ids: true
  toc_levels: 2..6
excerpt_separator: "<!--more-->"

# Custom theme settings
show_excerpts: true
linkedin_url: "https://www.linkedin.com/in/flemmingbakkensen/"
twitter_url: "https://x.com/fbakkensen"
github_url: "https://github.com/FBakkensen"
bluesky_url: "https://bsky.app/profile/fbakkensen.bsky.social"

# Collections for tags (GitHub Pages compatible)
collections:
  tags:
    output: true
    permalink: /tags/:name/

defaults:
  - scope:
      path: ""
      type: tags
    values:
      layout: tag